version: '3'
services:
  db:
    image: mariadb:10.1.34
    environment:
      PROXY_ADDRESS_FORWARDING: 'true'
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: metalwork
      MYSQL_USER: metalwork
      MYSQL_PASSWORD: 1234
    ports:
      - '3306:3306'
    restart: on-failure
    volumes:
      - ${PWD}/../../disks/sql:/var/lib/mysql

  keycloak:
    image: jboss/keycloak:12.0.4
    ports:
      - "6080:8080"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=mariadb
      - DB_USER=restaurant
      - DB_PASSWORD=1234
      - DB_ADDR=db
      - DB_DATABASE=keycloak
      - DB_PORT=3306
      - KEYCLOAK_IMPORT=/tmp/example-realm.json
    volumes:
      - ${PWD}/realm-export.json:/tmp/example-realm.json
    depends_on:
      - db